### ISSUE TITLE
Allow "paragraph" pagination option for electronic sources

### ISSUE THREAD

**Issue by farinc** [jmclawson/biblatex-mla#28]
I found that this style does not allow for "paragraph" pagination style. I tried using something like this:
```
@online{bedord_2017, 
title={How Automation Will Transform Farming}, 
url={https://www.agriculture.com/technology/robotics/how-automation-will-transform-farming}, 
journal={Successful Farming}, publisher={Meredith Corporation}, 
author={Bedord, Laurie}, 
year={2017}, 
month={Nov}, 
urldate={2021-05-06}, 
pagination = {paragraph},
pages={3-5}
}
```
But it doesn't place pars. in the bibliographic entry for the paragraph numbers 3-5 (I am using the answer at the stackexchange [question](https://tex.stackexchange.com/questions/372522/how-to-cite-paragraphs-rather-than-pages-from-bibliography-reference/591751) ). Instead it just puts "pp. 3-5"
I want this because according to Purdue Owl and their details of electronic citations ([link](https://owl.purdue.edu/owl/research_and_citation/mla_style/mla_formatting_and_style_guide/mla_works_cited_electronic_sources.html)) they say websites should be located by paragraph and thus they recommend using "pars / pars." in a citation entry instead of "p. / pp." 

Is there a way to do this that I am not familiar with?

**Comment by jmclawson** [comment]
From my understanding, the MLA guidelines here are indicating how to label paragraph numbers within individual parenthetical citations. By contrast, this `pagination` field refers to the way pages are indicated in the list of Works Cited at the end of a paper. This field should show the _entire_ page range of a title---an article, an essay in a collection, an Introduction, etc. It shouldn't indicate only the limited range of pages/paragrphs cited within your writing, so online works comporting to MLA standards should probably avoid the `pages` field entirely in the `.bib` file. (Unless there's something I'm not considering?)

As indicated in the StackExchange page you've linked, this field is meant to change the label before numbers in citations. Postnotes in citations made by biblatex-mla do not print a label (i.e., "pp." or "pages") because MLA style omits these labels when unnecessary. Of course, sometimes they're necessary. If you'd like to indicate that the number in your postnote refers to a paragraph instead of a page, you can add this label in the brackets: `\autocite[pars.\ 3--5]{bedord_2017}`.

It may be desirable for biblatex-mla to support the `pagination` field to add the label in citations, but this is low priority, and I'd only like to do it if it can be done well. From my recollection, these labels only need to be printed once to indicate that citations from this source refer to something other than pages, with subsequent citations taking it as known. There are already problems I can imagine when a citation for a long poem like _The Waste Land_ wants to point to a footnote instead of a line number. At the moment, we avoid these edge cases by following MLA guidelines to print no label in citations by default.

**Comment by jmclawson** [comment]
I've been revisiting this issue today, and I've now added the ability to automatically add non-page labels "pars." before a postnote in a citation. These changes are available on GitHub, and they'll be part of the next release submitted to CTAN. Please be aware that the implementation is different from what was requested.

Biblatex makes two fields available for adding these labels to two places, and biblatex-mla now supports these:

1. The `pagination` field determines the label to come before the page number page (or "line" / "par." /  "column" / etc. number) **inside a citation**.
2. The `bookpagination` field determines the label to come before the page number (or "line" / "par." / "column" / etc. number) **inside a bibliography entry**.

Although the field names are not as clear as one might hope for, the distinction makes sense. Citations tell _where within a work_ a particular quotation or paraphrase is drawn from, but the bibliographic needs to tell _where within the world_ a work can be found. A citation might point to line 5 of a poem, but the bibliographic entry needs to point to page 35 of the poetry collection.

For this reason, your example bibliography is not well formed. Here's a suggested revision:
```
@online{bedord_2017, 
title={How Automation Will Transform Farming}, 
url={https://www.agriculture.com/technology/robotics/how-automation-will-transform-farming}, 
journal={Successful Farming}, publisher={Meredith Corporation}, 
author={Bedord, Laurie}, 
year={2017}, 
month={Nov}, 
urldate={2021-05-06}, 
pagination = {paragraph},
}
```

I've removed the `pages` field, since web pages don't typically have fixed page numbers assigned to them. The citation to paragraphs 3-5 would come like this: `\autocite[3-5]{bedord_2017}`

Before submitting an update to CTAN, I'll want to step through all possible key values to see if any others need abbreviated: I've already applied `paragraph` and `paragraphs` on GitHub.
